[server]
enableStaticServing = true

[theme]
# Spotify
# What's missing/doesn't look great:
# - ✅ buttons are completely rounded, even though other elements are not
# - ✅ when hovering buttons, only the border color becomes white
# - ✅ header font sizes
# - they use pills pretty heavily, but theirs have gray background and no border, become slightly lighter when hovering, and white when selected
base = "dark"
primaryColor = "#1ED760"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
sidebarBackgroundColor = "#000000"
sidebarSecondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showBorderAroundInputs = false
roundness = 0.18
font = "CircularSpotifyText"

[[theme.fontFaces]]
url = "http://localhost:8502/app/static/CircularSpotifyText-Medium.otf"
family = "CircularSpotifyText"
style = "normal"
