[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#1ED760"
backgroundColor = "#121212"
secondaryBackgroundColor = "#333333"
sidebarBackgroundColor = "#000000"
sidebarSecondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
linkColor = "#9D9D9D"
borderColor = "#7F7F7F"
showBorderAroundInputs = false
roundness = 0.18
font = "CircularSpotifyText"

[[theme.fontFaces]]
url = "app/static/CircularSpotifyText-Medium.otf"
family = "CircularSpotifyText"
style = "normal"
